sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
     secure: "I2itx/9u3s8Wk4H/FpIuyXonUbLg8taCQKFbi/FdQ2oj+N2rwlriPizYNQBxh62V98eSUIV9jZNI8NmHuI0LEQJJZlcabvQ++jcVllrefmyldgd5NKT+KajFQejzG1r7HTlwuNDOGbv+36REboC0T35oOQgIIBF8LWBEA2LyYD1fE9d9xV0nD88dWUmgkaIMc8HhMOqBRSgObWKytqiqNno6APecuSwc+0wgxkVhoU3rMsXxkOplVW5r68TKbm7RADxIT0bOdYeakleWP5i4WwFI29qBRIaEp3R2dBq9MvUn1ecYwLpYF8PTHETdfWQuPbbCOMfKBgVglp15Jcef1b3H5udDhvZ0Znd8l0VKwLnvcXgBWYDgCt30IIQE7eYkbSed6CpKYLhqZP+S9K12xcRZ5P1whV3CGx8NCXoZyXNojh07Bd/0Trw3CT/XI1vHF3YA6vGXYDySp4xBiVk127EU0OGoEwlJ7yoBLbgQFxl+b7t4q7iILYxzJY4qq2GV8d4SIxiL9Z9NWLWlQMQotEC/IWCj820Ql8k3KoqmqSfauTfkNAOd3Cics06uJDHnNWJinx/rgx8BljUsZJThLRoiySZtYsOVCZ9Ho3N/72e0eAg6MPZQaaW6hVw0jxoIry54/yHe8XJcQZ2NPJeO9qqMfcZULULJnVxQ6j4l/qY="
  branches:
  only:
    - source
